import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useSelector, useDispatch } from 'react-redux'
import { setUserData } from '../slices/userSlice'
import { fetchData, } from '../slices/userSlice'
import { useRouter } from 'next/router'
import Header from '../components/Header'
import Main from '../components/Main'

export default function Home() {
  const user = useSelector((state) => state.user.value)

  const followStatus = useSelector((state) => state.user.followValue)
  const fulfilledStatus = useSelector((state) => state.user.isFulfilled)
  const dispatch = useDispatch()
  const router = useRouter()

  const [followerData, setFollowerData] = useState([])

  useEffect(() => {
    dispatch(fetchData())
  }, [])

  

  useEffect(() => {
    setFollowerData([])

    fulfilledStatus
      ? user.data.map((item) => {
          axios
            .get(`https://api.twitch.tv/helix/users?login=${item.to_login}`, {
              headers: {
                'Client-Id': 'mz3oo6erk0hqgzs6o8ydh26c9m8u09',
                Authorization: `Bearer ${document?.location?.hash.slice(
                  14,
                  44
                )}`,
              },
            })
            .then((res) => {
              setFollowerData((followerData) => [
                ...followerData,
                res.data.data[0],
              ])
            })
        })
      : null

      
  }, [fulfilledStatus])

  

  
  return (
    <div className="bg-gray-300 h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main followerData={followerData}/>
      
      

      

      
    </div>
  )
}
