import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useSelector, useDispatch } from 'react-redux'
import { setUserData } from '../slices/userSlice'
import { fetchData } from '../slices/userSlice'
import { useRouter } from 'next/router'

export default function Home() {
  const user = useSelector((state) => state.user.value)
  const fulfilledStatus = useSelector((state) => state.user.isFulfilled)
  const dispatch = useDispatch()
  const router = useRouter()

  const [followerData, setFollowerData] = useState([])



  

  

 useEffect(() => {
  dispatch(fetchData())
 }, [])

 useEffect(() => {
  setFollowerData([])

fulfilledStatus ? (user.data.map((item) => {
    axios.get(`https://api.twitch.tv/helix/users?login=${item.to_login}`,
    {
      headers: {
        'Client-Id': 'mz3oo6erk0hqgzs6o8ydh26c9m8u09',
        Authorization: `Bearer ${document?.location?.hash.slice(14, 44)}`,
      },
    }
    )
    .then((res) => {
      setFollowerData((followerData) => [...followerData, res.data.data[0]])
    })
  })) : null
  
 }, [fulfilledStatus])

 console.log(followerData)
  return (
    <div className='bg-gray-300 h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p className='text-black'>{user ? user[0]?.id : 'null'}</p>
      
      <div className='bg-purple-500 w-36 p-1 rounded-2xl text-white font-bold text-center' onClick={() => router.push('https://id.twitch.tv/oauth2/authorize?response_type=token&client_id=mz3oo6erk0hqgzs6o8ydh26c9m8u09&redirect_uri=http://localhost:3000&scope=user%3Aread%3Afollows&state=c3ab8aa609ea11e793ae92361f002671')}>{document.location.hash ? 'Connected' : 'Connect to Twitch'}</div>
    </div>
  )
}
