import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useSelector, useDispatch } from 'react-redux'
import { setUserData } from '../slices/userSlice'
import { fetchData } from '../slices/userSlice'
import { useRouter } from 'next/router'
import Header from '../components/Header'
import Main from '../components/Main'
import Vods from '../components/Vods'

export default function Home() {
  const user = useSelector((state) => state.user.value)

  const connectedUser = useSelector((state) => state.user.followValue)
  const fulfilledStatus = useSelector((state) => state.user.isFulfilled)
  const dispatch = useDispatch()
  const router = useRouter()

  const [followerData, setFollowerData] = useState([])

  const [vodData, setVodData] = useState([])

  const [finished, setFinished] = useState(false)

  const [open, setOpen] = useState(false)

  const [filteredArray, setFilteredArray] = useState([])

  const [searchInput, setSearchInput] = useState('')

  const [currentFollower, setCurrentFollower] = useState()

  function handleChange(e) {
    setSearchInput(e.target.value)
    const localSearch = e.target.value
    const copyArr = [...followerData]
    console.log(localSearch)
    const filtered = copyArr.filter((item) => {
      return item[0].login.includes(localSearch)
    })

    setFilteredArray([...filtered])
  }

  useEffect(() => {
    if (followerData.length == 0) {
      setFollowerData([])

      fulfilledStatus
        ? user.data.map((item, index) => {
            axios
              .get(`https://api.twitch.tv/helix/users?login=${item.to_login}`, {
                headers: {
                  'Client-Id': 'mz3oo6erk0hqgzs6o8ydh26c9m8u09',
                  Authorization: `Bearer ${document?.location?.hash.slice(
                    14,
                    44
                  )}`,
                },
              })
              .then((res) => {
                return res.data.data[0]
              })
              .catch((error) => {
                console.log(error)
              })
              .then((res2) => {
                axios
                  .get(
                    `https://api.twitch.tv/helix/videos?user_id=${res2?.id}&first=3&sort=time&type=archive`,
                    {
                      headers: {
                        'Client-Id': 'mz3oo6erk0hqgzs6o8ydh26c9m8u09',
                        Authorization: `Bearer ${document?.location?.hash.slice(
                          14,
                          44
                        )}`,
                      },
                    }
                  )
                  .then((res) => {
                    setFollowerData((followerData) => [
                      ...followerData,
                      [res2, res.data],
                    ])
                    // setFilteredArray((followerData) => [
                    //   ...followerData,
                    //   [res2, res.data],
                    // ])
                  })
              })
          })
        : null
    }
  }, [fulfilledStatus])

  useEffect(() => {
    dispatch(fetchData())
  }, [])

  console.log(user)

  return (
    <div className="bg-gray-900 h-full flex flex-col relative overflow-x-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        followerData={followerData}
        filteredArray={filteredArray}
        setFilteredArray={setFilteredArray}
        searchInput={searchInput}
        setSearchInput={setSearchInput}
        handleChange={handleChange}
      />
      {open ? (
        <Vods
          followerData={followerData}
          open={open}
          setOpen={setOpen}
          currentFollower={currentFollower}
          setCurrentFollower={setCurrentFollower}
        />
      ) : null}

      <Main
        followerData={followerData}
        filteredArray={filteredArray}
        setFilteredArray={setFilteredArray}
        searchInput={searchInput}
        setSearchInput={setSearchInput}
        open={open}
        setOpen={setOpen}
        currentFollower={currentFollower}
        setCurrentFollower={setCurrentFollower}
      />
    </div>
  )
}
